stepName: jobs - cancel and purge
description: You can use this operation to cancel a job and purge its output.
endpoint: '/restjobs/jobs/'
method: DELETE
hasConfig: true
attachCredentials: true
basicAuth: true
resultProperty:
  show: true
  format:
    - json
    - propertySheet
  default: /myJob/deleteJob
parameters:
  - property: jobname
    type: entry
    label: Jobname
    documentation: Identifies the job for which the spool files are to be listed. Use either the job name and job ID combination or the job correlator to identify the job.
    required: 0
  - property: jobid
    type: entry
    label: Jobid
    documentation:  Identifies the job for which the spool files are to be listed. Use either the job name and job ID combination or the job correlator to identify the job.
    required: 0
  - property: correlator
    type: entry
    label: Correlator
    htmlDocumentation: |-  
      <pre>Identifies the job for which the spool files are to be listed. Use either the job name and job ID combination or the job correlator to identify the job.
      To use a job correlator on this request, specify the full job correlator for the job: The 31-byte system portion, a semicolon, and the user portion (up to 32 bytes). 
      The correlator can be one that you have obtained from the "job-correlator" property in a returned JSON job document. Alternatively, you can specify the complete URL as provided in the "url" property of a JSON job document.</pre>
    required: 0
  - property: X-IBM-Job-Modify-Version
    type: select
    label: X-IBM-Job-Modify-Version
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: 1.0 - process asynchronously
        value: 1.0
      - name: 2.0 - process synchronously
        value: 2.0        
    htmlDocumentation: |-  
      <pre style="white-space:pre-wrap; word-wrap:break-word;">Use this header to specify whether the request is to be processed asynchronously or synchronously, as follows:
      1.0
      Specifies that the request is to be processed asynchronously. In response, the caller receives an HTTP status code of 202 Accepted, with no indication of the success or failure of the request. To verify that the initial request was performed, the caller can issue the service described in Obtain the status of a job.
      2.0
      Specifies that the request is to be processed synchronously. In response, the caller receives an HTTP status code, which indicates the results of the request. For a successful request, the caller also receives the JSON job feedback document, which includes details about the job that was cancelled.
      If this header is omitted, the request is processed asynchronously by default.

      Synchronous processing is supported for JES2 only. On systems running JES3, the z/OS jobs REST interface services must run asynchronously.</pre>
    required: 0
