---

#perl RESTPluginWizard/build.pl --plugin-wizard-folder ./PluginWizard --plugin-name EC-zOSMF --config EC-zOSMF/config/EC-zOSMF.yaml --workspace . &&  rsync -avz --delete ./EC-zOSMF/ --exclude '.git' nick@10.200.1.150:EC-zOSMF/
#
# This block refers to auto help generation
help:
  title: Electric Flow integration for zOSMF
  description: |
    This plugin allows to work with zOSMF REST API.
  links:
    - https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_RESTServices.htm
  hasConfig: true
procedures:
####Jobs section
  - name: Jobs - Submit a job
    stepName: jobs - submit a job
    description: You can use this operation to submit a job to run on z/OS.
    # https://{instance}/DefaultCollection/_apis/wit/workitems?api-version={version}&ids={string}[&fields={string}&asOf={DateTime}&$expand={enum{relations}&ErrorPolicy={string}]
    endpoint: '#{{hostUrl}}/restjobs/jobs'
    #  #{{instance}} means that "instance" will ba taken from config
    # #{repository} will be taken from the procedure parameters
    method: PUT
    # HTTP method
    hasConfig: true
     # a field for configuration name will be added to the form
    attachCredentials: true
    contentType: text/plain
     # credentials will be attached to the procedure
    basicAuth: true
     # credentials will be turned into basic auth header
    # if no credentials found, the procedure won't fail, the request will be made without credentials

    # The result will be saved in this property
    resultProperty:
      show: true
      # Selectbox with formats will appear
      format:
        - json
        - propertySheet
      default: /myJob/submitJob
    parameters:
      - property: code
        in: body
        type: textarea
        label: JCL app to run
        documentation: JCL code that is going to be run
        required: 1
      - property: cache-control: no-cache
  
####Data Set Section

# List the z/OS data sets on a system Start of changeGET /zosmf/restfiles/ds?dslevel=<dataset_name_pattern>[&volser=<volser>&start=<dsname>]End of change
  - name: Data Set - List zOS data sets on a system
    stepName: data set - list zOS data sets on a system
    description: List the z/OS data sets on a system.
    # https://{instance}/DefaultCollection/_apis/wit/workitems?api-version={version}&ids={string}[&fields={string}&asOf={DateTime}&$expand={enum{relations}&ErrorPolicy={string}]
    endpoint: '#{{hostUrl}}/restfiles/ds'
    #  #{{instance}} means that "instance" will ba taken from config
    # #{repository} will be taken from the procedure parameters
    method: GET
    # HTTP method
    hasConfig: true
     # a field for configuration name will be added to the form
    attachCredentials: true
     # credentials will be attached to the procedure
    basicAuth: true
     # credentials will be turned into basic auth header
    # if no credentials found, the procedure won't fail, the request will be made without credentials

    # The result will be saved in this property
    resultProperty:
      show: true
      # Selectbox with formats will appear
      format:
        - json
        - propertySheet
      default: /myJob/datasetList
    parameters:
      - property: dslevel
        in: query
        type: entry
        label: Dslevel
        documentation: The search parameter that identifies the cataloged data sets to be listed.
        required: 1
      - property: volser
        in: query
        type: entry
        label: Volser
        documentation: A parameter that identifies the volume serials to be searched for data sets with names that match the specified dslevel parameter.
        required: 0
      - property: start_num
        in: query
        type: entry
        label: Start
        documentation: An optional search parameter that specifies the first data set name to return in the response document. The length of the data set name that you specify cannot exceed 44 characters, and cannot contain wildcards. If the data set name is not found for the given search, then the next data set matching the search will be returned.
        required: 0
      - property: X-IBM-Attributes
        label: X-IBM-Attributes. If not set - dsname used.
        type: select
        in: header
        option:
          - name: dsname
            value: dsname
          - name: base
            value: base
          - name: vol
            value: vol
        documentation: Extends search.
        value: none
      - property: X-IBM-Max-Items
        in: header
        type: entry
        label: Max items returned (1000 max, 0 means no limit)
        value: 0
        documentation: This header value specifies the maximum number of items to return. To request that all items be returned, set this header to 0. If you omit this header, or specify an incorrect value, up to 1000 items are returned by default.
        required: 0
      - property: totalRows
        type: checkbox
        label: Return totalRows
        documentation: If checked, then "totalRows" property is returned if more data sets than the maximum requested are available.
        required: 0





# List the members of a z/OS data set Start of changeGET /zosmf/restfiles/ds/<dataset_name>/member?start=<member>&pattern=<mem-pat>End of change

# Retrieve the contents of a z/OS data set or member  GET /zosmf/restfiles/ds/[-(<volser>)/]<data-set-name>[(<member-name>)]
#----

# Write data to a z/OS data set or member PUT /zosmf/restfiles/ds/[-(<volser>)/]<data-set-name>[(<member-name>)]
  - name: Data Set - Write data to a zOS data set or member
    stepName: data set - write data to a zos data set or member
    description: You can use this operation to write data to an existing sequential data set, or a member of a partitioned data set (PDS or PDSE). To write to an uncataloged data set, include a volume serial on the request.
    # https://{instance}/DefaultCollection/_apis/wit/workitems?api-version={version}&ids={string}[&fields={string}&asOf={DateTime}&$expand={enum{relations}&ErrorPolicy={string}]
    endpoint: '#{{hostUrl}}/zosmf/restfiles/ds/'
    #[-(<volser>)/]<data-set-name>[(<member-name>)]
    #  #{{instance}} means that "instance" will ba taken from config
    # #{repository} will be taken from the procedure parameters
    method: PUT
    # HTTP method
    hasConfig: true
     # a field for configuration name will be added to the form
    attachCredentials: true
     # credentials will be attached to the procedure
    basicAuth: true
     # credentials will be turned into basic auth header
    # if no credentials found, the procedure won't fail, the request will be made without credentials

    # The result will be saved in this property
    resultProperty:
      show: true
      # Selectbox with formats will appear
      format:
        - json
        - propertySheet
      default: /myJob/createDataset
    parameters:
      - property: dataset-name
        type: entry
        label: Data set name
        documentation: The name of a z/OS data set that you are going to create.
        required: 1
      - property: volser
        type: entry
        label: Volser
        documentation: A parameter that identifies the volume serials to be searched for data sets with names that match the specified dslevel parameter.
        required: 0
      - property: member-name
        type: entry
        label: Member name
        documentation: Identifies the name of the PDS or PDSE member to which to write. Include this parameter for a PDS or PDSE member write request.
        required: 0
      - property: Content-Type
        in: header
        type: entry
        label: Content Type
        documentation: The data is interpreted according to the content-type as one of binary, text, record or 'diff -e' format according a combination of the "Content-Type" and the value of the X-IBM-Data-Type custom header, if present.
        required: 0
      - property: X-IBM-Data-Type
        label: X-IBM-Data-Type
        type: select
        in: header
        option:
          - name: text
            value: text
          - name: binary
            value: binary
          - name: record
            value: record
        documentation: When set to 'text' and "Content-Type" is "application/x-ibm-diff-e", the input consists of commands in the same format as produced by the z/OS UNIX 'diff -e' command. These commands are used to add, replace and delete lines in the target data set.
      - property: X-IBM-Migrated-Recall
        label: X-IBM-Migrated-Recall
        type: select
        in: header
        option:
          - name: wait
            value: wait
          - name: nowait
            value: nowait
          - name: record
            value: nowait
        documentation: This header is optional; use it to specify how a migrated data set is handled. By default, a migrated data set is recalled synchronously.
      - property: X-IBM-Obtain-ENQ
        label: X-IBM-Obtain-ENQ
        type: select
        in: header
        option:
          - name: None
            value: 
          - name: EXCL
            value: EXCL
          - name: SHRW
            value: SHRW        
        documentation: This header is optional; set it to one of the following values to request that a system ENQ be obtained and held after the completion of this request. If not specified, then no ENQs will be held after the completion of this request. A successful response will include an X-IBM-Session-Ref response header that can be added as a request header to subsequent requests to specify affinity to the TSO address space holding this ENQ.
      - property: X-IBM-Session-Ref
        label: X-IBM-Session-Ref
        type: entry
        in: header
        documentation: This header is optional; include it with the value returned from a previous X-IBM-Session-Ref response header to indicate that your request should be executed in the TSO address space that was previously reserved with a X-IBM-Obtain-ENQ request header. This address space will not be used for other requests and if not used at least once every 10 minutes it will be terminated. The X-IBM-Obtain-ENQ and X-IBM-Session-Ref headers are mutually exclusive.
      - property: X-IBM-Release-ENQ
        label: X-IBM-Release-ENQ
        type: entry
        in: header
        documentation: This header is optional; it may be specified with a value "true" to request that the ENQ held by the associated TSO address space be released. This header must be specified along with a valid X-IBM-Session-Ref header.



# Start of changeCreate a sequential and partitioned data setEnd of change  Start of changePOST /zosmf/restfiles/ds/<data-set-name>End of change
  - name: Data Set - Create a sequential and partitioned data set
    stepName: data set - create a sequential and partitioned data set
    description: You can use this operation to create sequential and partitioned data sets on a z/OS system.
    # https://{instance}/DefaultCollection/_apis/wit/workitems?api-version={version}&ids={string}[&fields={string}&asOf={DateTime}&$expand={enum{relations}&ErrorPolicy={string}]
    endpoint: '#{{hostUrl}}/restfiles/ds/#{dataset-name}'
    #  #{{instance}} means that "instance" will ba taken from config
    # #{repository} will be taken from the procedure parameters
    method: POST
    contentType: application/json
    # HTTP method
    hasConfig: true
     # a field for configuration name will be added to the form
    attachCredentials: true
     # credentials will be attached to the procedure
    basicAuth: true
     # credentials will be turned into basic auth header
    # if no credentials found, the procedure won't fail, the request will be made without credentials

    # The result will be saved in this property
    resultProperty:
      show: true
      # Selectbox with formats will appear
      format:
        - json
        - propertySheet
      default: /myJob/createDataset
    parameters:
      - property: dataset-name
        type: entry
        label: Data set name
        documentation: The name of a z/OS data set that you are going to create.
        required: 1
      - property: volser
        in: body
        type: entry
        label: Volser
        documentation: A parameter that identifies the volume serials to be searched for data sets with names that match the specified dslevel parameter.
        required: 0
      - property: unit
        in: body
        type: entry
        label: Unit
        documentation: Device type.
        required: 0
      - property: dsorg
        in: body
        type: entry
        label: Dsorg
        documentation: Data set organization.
        required: 0
      - property: alcunit
        in: body
        type: entry
        label: Alcunit
        documentation: Unit of space allocation.
        required: 0
      - property: primary
        in: body
        type: entry
        label: Primary
        documentation: Primary space allocation.
        required: 0
      - property: secondary
        in: body
        type: entry
        label: Secondary
        documentation: Secondary space allocation.
        required: 0
      - property: dirblk
        in: body
        type: entry
        label: Dirblk
        documentation: Number of directory blocks.
        required: 0
      - property: avgblk
        in: body
        type: entry
        label: Avgblk
        documentation: Average block.
        required: 0
      - property: recfm
        in: body
        type: entry
        label: Recfm
        documentation: Record format.
        required: 0
      - property: blksize
        in: body
        type: entry
        label: Blksize
        documentation: Block size.
        required: 0
      - property: lrecl
        in: body
        type: entry
        label: Lrecl
        documentation: Record length.
        required: 0
      - property: storeclass
        in: body
        type: entry
        label: Storeclass
        documentation: Storage class.
        required: 0
      - property: mgntclass
        in: body
        type: entry
        label: Mgntclass
        documentation: Storage class.
        required: 0
      - property: dataclass
        in: body
        type: entry
        label: Dataclass
        documentation: Data class.
        required: 0

# Start of changeDelete a sequential and partitioned data setEnd of change  Start of changeDELETE /zosmf/restfiles/ds/<data-set-name>
#---
# DELETE /zosmf/restfiles/ds/-(<volume>)/<data-set-name>
#---


# End of change
# Start of changeDelete a partitioned data set memberEnd of change  Start of changeDELETE /zosmf/restfiles/ds/<dataset-name>(<member-name>)End of change
# Start of changez/OS Data set and member utilitiesEnd of change  Start of changePUT /zosmf/restfiles/ds/<to-data-set-name>End of change
# Start of changeAccess Method Services InterfaceEnd of change  Start of changePUT /zosmf/restfiles/amsEnd of change
# List the files and directories of a UNIX file path  GET /zosmf/restfiles/fs?path=<file-path-name>

#---

# Retrieve the contents of a z/OS UNIX file GET /zosmf/restfiles/fs/<file-path-name>
# Write data to a z/OS UNIX file  PUT /zosmf/restfiles/fs/<filepath-name>

#---
# Start of changeCreate a UNIX file or directoryEnd of change Start of changePOST /zosmf/restfiles/fs/<file-path-name>End of change
# Start of changeDelete a UNIX file or directoryEnd of change Start of changeDELETE /zosmf/restfiles/fs/<file-pathname>End of change
# Start of changez/OS UNIX file utilitiesEnd of change  Start of changePUT /zosmf/restfiles/fs/<file-path-name>End of change
# Start of changeList z/OS UNIX FilesystemsEnd of change  Start of changeGET /zosmf/restfiles/mfs/End of change
# Start of changeCreate z/OS UNIX zFS FilesystemEnd of change Start of changePOST /zosmf/restfiles/mfs/zfs/<file-system-name>End of change
# Start of changeDelete z/OS UNIX zFS FilesystemEnd of change Start of changeDELETE /zosmf/restfiles/mfs/zfs/<file-system-name>End of change
# Start of changeMount a UNIX file systemEnd of change  Start of changePUT /zosmf/restfiles/mfs/<file-system-name>End of change
# Start of changeUnmount a UNIX file systemEnd of change  Start of changePUT /zosmf/restfiles/mfs/<file-system-name>End of change

