---

#perl RESTPluginWizard/build.pl --plugin-wizard-folder ./PluginWizard --plugin-name EC-zOSMF --config EC-zOSMF/config/EC-zOSMF.yaml --workspace . &&  rsync -avz --delete ./EC-zOSMF/ --exclude '.git' nick@10.200.1.150:EC-zOSMF/
#&& sshpass -p "" ssh 10.200.1.150 "cd ~ && ./i_zOSMF.sh"
# This block refers to auto help generation
help:
  title: Electric Flow integration for zOSMF
  description: |
    This plugin allows to work with zOSMF REST API.
  links:
    - https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_RESTServices.htm
  hasConfig: true
procedures:
  - name: System - Info
    $ref: ./Other/info.yaml

  - name: Data Set - List
    $ref: ./DataSet/list.yaml

  - name: Data Set - Read data
    $ref: ./DataSet/readData.yaml

  - name: Data Set - Write data
    $ref: ./DataSet/writeData.yaml

  - name: Data Set - Create
    $ref: ./DataSet/create.yaml

  - name: Data Set - Delete
    $ref: ./DataSet/delete.yaml
  
  - name: Jobs - Spool files list
    $ref: ./Jobs/spoolFilesList.yaml

  - name: Jobs - Get spool file content
    $ref: ./Jobs/spoolFileContent.yaml

  - name: Jobs - Submit a job
    $ref: ./Jobs/submit.yaml

  - name: Jobs - List 
    $ref: ./Jobs/list.yaml

  - name: Jobs - Cancel and Purge
    $ref: ./Jobs/delete.yaml

  - name: Jobs - Obtain status
    $ref: ./Jobs/status.yaml

