stepName: data set - create a sequential and partitioned data set
description: You can use this operation to create sequential and partitioned data sets on a z/OS system.
endpoint: '/restfiles/ds/#{dataset-name}'
method: POST
contentType: application/json
hasConfig: true
attachCredentials: true
basicAuth: true
resultProperty:
  show: true
  format:
    - json
    - propertySheet
  default: /myJob/createDataset
parameters:
  - property: dataset-name
    type: entry
    label: Data set name
    documentation: The name of a z/OS data set that you are going to create.
    required: 1
  - property: volser
    in: body
    type: entry
    label: Volser
    refiner: remove_blank_header
    documentation: A parameter that identifies the volume serials to be searched for data sets with names that match the specified dslevel parameter.
    required: 0
  - property: unit
    in: body
    type: entry
    label: Unit
    refiner: remove_blank_header
    documentation: Device type.
    required: 0
  - property: dsorg
    in: body
    type: entry
    label: Dsorg
    refiner: remove_blank_header
    documentation: Data set organization.
    required: 0
  - property: alcunit
    in: body
    type: entry
    label: Alcunit
    refiner: remove_blank_header
    documentation: Unit of space allocation.
    required: 0
  - property: primary
    in: body
    type: entry
    label: Primary
    refiners: 
      - convert_to_int
      - remove_blank_header
    validators:
      - is_int
    documentation: Primary space allocation.
    required: 0
  - property: secondary
    in: body
    type: entry
    label: Secondary
    refiners: 
      - convert_to_int
      - remove_blank_header
    validators:
      - is_int
    documentation: Secondary space allocation.
    required: 0
  - property: dirblk
    in: body
    type: entry
    label: Dirblk
    refiners: 
      - convert_to_int
      - remove_blank_header
    validators:
      - is_int
    documentation: Number of directory blocks.
    required: 0
  - property: avgblk
    in: body
    type: entry
    label: Avgblk
    refiners: 
      - convert_to_int
      - remove_blank_header
    validators:
      - is_int
    documentation: Average block.
    required: 0
  - property: recfm
    in: body
    type: entry
    label: Recfm
    refiners: remove_blank_header
    documentation: Record format.
    required: 0
  - property: blksize
    in: body
    type: entry
    label: Blksize
    refiners: 
      - convert_to_int
      - remove_blank_header
    validator: is_int
    documentation: Block size.
    required: 0
  - property: lrecl
    in: body
    type: entry
    label: Lrecl
    refiners: 
      - convert_to_int
      - remove_blank_header
    validators:
      - is_int
    documentation: Record length.
    required: 0
  - property: storeclass
    in: body
    type: entry
    label: Storeclass
    refiner: remove_blank_header
    documentation: Storage class.
    required: 0
  - property: mgntclass
    in: body
    type: entry
    label: Mgntclass
    refiner: remove_blank_header
    documentation: Storage class.
    required: 0
  - property: dataclass
    in: body
    type: entry
    label: Dataclass
    refiner: remove_blank_header
    documentation: Data class.
    required: 0