stepName: data set - delete a sequential and partitioned data set
description: You can use this operation to delete sequential and partitioned data sets on a z/OS system.
# https://{instance}/DefaultCollection/_apis/wit/workitems?api-version={version}&ids={string}[&fields={string}&asOf={DateTime}&$expand={enum{relations}&ErrorPolicy={string}]
endpoint: '/restfiles/ds/#{dataset-name}'
#[-(<volser>)/]<data-set-name>[(<member-name>)]
#  #{{instance}} means that "instance" will ba taken from config
# #{repository} will be taken from the procedure parameters
method: DELETE
# HTTP method
hasConfig: true
 # a field for configuration name will be added to the form
attachCredentials: true
 # credentials will be attached to the procedure
basicAuth: true
 # credentials will be turned into basic auth header
# if no credentials found, the procedure won't fail, the request will be made without credentials

# The result will be saved in this property
resultProperty:
  show: true
  # Selectbox with formats will appear
  format:
    - json
    - propertySheet
  default: /myJob/deleteDataset
parameters:
  - property: dataset-name
    type: entry
    label: Data set name
    documentation: The name of a z/OS data set, that you are going to delete.
    required: 1
  - property: volume
    type: entry
    label: Volume
    documentation:  Volume is where the data set is resided, when the data set is uncatalogued.
    required: 0