stepName: data set - delete a sequential and partitioned data set
description: You can use this operation to delete sequential and partitioned data sets on a z/OS system.
endpoint: '/restfiles/ds/#{dataset-name}'
method: DELETE
hasConfig: true
attachCredentials: true
basicAuth: true
resultProperty:
  show: true
  format:
    - json
    - propertySheet
  default: /myJob/deleteDataset
parameters:
  - property: dataset-name
    type: entry
    label: Data set name
    documentation: The name of a z/OS data set, that you are going to delete.
    required: 1
  - property: volume
    type: entry
    label: Volume
    documentation:  Volume is where the data set is resided, when the data set is uncatalogued.
    required: 0