stepName: data set - retrieve the contents of a zOS data set or member
description: You can use this operation to retrieve the contents of a sequential data set, or a member of a partitioned data set (PDS or PDSE). To retrieve the contents of an uncataloged data set, include the volume serial on the request.
endpoint: '/restfiles/ds/#{dataset-name}'
method: GET
hasConfig: true
attachCredentials: true
basicAuth: true
resultProperty:
  show: true
  format:
    - json
    - propertySheet
    - file
  default: /myJob/readDataset
parameters:
  - property: dataset-name
    type: entry
    label: Data set name
    documentation: The name of a z/OS data set that you are going to create.
    required: 1
  - property: volser
    type: entry
    label: Volser
    documentation: A parameter that identifies the volume serials to be searched for data sets with names that match the specified dslevel parameter.
    required: 0
  - property: member-name
    type: entry
    label: Member name
    documentation: Identifies the name of the PDS or PDSE member to which to write. Include this parameter for a PDS or PDSE member write request.
    required: 0
  - property: If-None-Match
    label: If-None-Match
    type: entry
    in: header
    refiner: remove_blank_header
    documentation: This header is optional; use it to specify the ETag token to be used to correlate this request with a previous request. If the data on the z/OS host has not changed since the ETag token was generated, z/OSMF returns a status of HTTP 304 Not Modified. For the initial request to the resource, you can omit this header.
  - property: X-IBM-Data-Type
    label: X-IBM-Data-Type
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: text
        value: text
      - name: binary
        value: binary
      - name: record
        value: record
    documentation: This header is optional; use it to indicate whether data conversion is to be performed on the returned data. When set to text, data conversion is performed. The data transfer process converts each record from EBCDIC to the charset specified on the "Content-Type" header of the request. If no charset is specified, the default is ISO8859-1. A newline (NL) character from the response charset is inserted between logical records. For data sets with fixed-length records, trailing blanks are removed. When set to binary, no data conversion is performed. The data transfer process returns each record as-is, without translation. No delimiters are added between records. The response Content-Type is "application/octet-stream". When set to record, no data conversion is performed. Each logical record is preceded by the 4-byte big endian record length of the record that follows. This length does not include the prefix length. So, a zero-length record is 4 bytes of zeros with nothing following. If you omit this header, the default is text; the response is converted.
  - property: X-IBM-Return-Etag
    label: X-IBM-Return-Etag
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: true
        value: true
    documentation: This header is optional; set it to 'true' to force the response to include an "Etag" header, regardless of the size of the response data. If this header is not present or set to something other than 'true', then the default is to only send an Etag in the response for data sets smaller than a system determined length, which is at least 8MB. If X-IBM-Record-Range is present, then this header may not be specified with the value "true" and an Etag will never be returned.End of change. If this header is enabled for very large data sets, then performance is impacted since the data set must be read twice by the system.
  - property: X-IBM-Migrated-Recall
    label: X-IBM-Migrated-Recall
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: wait
        value: wait
      - name: nowait
        value: nowait
      - name: record
        value: nowait
    documentation: This header is optional; use it to specify how a migrated data set is handled. By default, a migrated data set is recalled synchronously.
  - property: X-IBM-Record-Range
    type: entry
    label: X-IBM-Record-Range
    in: header
    refiners: remove_blank_header
    htmlDocumentation: |-  
      <pre>Use this header to retrieve a range of records from a data set. You can specify this range using either of the following formats:
      SSS-EEE
      Where SSS identifies the start record and EEE identifies the end record to be retrieved. Both values are relative offsets (0-based).
      When EEE is set to 0, records through the end of the data set are retrieved.
      When SSS is omitted (i.e. -EEE), the final EEE records of the data set are retrieved.
      SSS,NNN
      Where SSS identifies the start record and NNN identifies the number of records to be retrieved.
      NNN must be greater than zero.
      Usage notes:
      If X-IBM-Record-Range is specified, then an ETag header will not be returned and the If-None-Match request header is ignored.
      If X-IBM-Record-Range header is present on the request, then header X-IBM-Return-Etag=true may not be specified.
      If no records are found in the range specified, an exception is returned.</pre>
    required: 0
  - property: X-IBM-Obtain-ENQ
    label: X-IBM-Obtain-ENQ
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: None
        value: 
      - name: EXCL
        value: EXCL
      - name: SHRW
        value: SHRW        
    documentation: This header is optional; set it to one of the following values to request that a system ENQ be obtained and held after the completion of this request. If not specified, then no ENQs will be held after the completion of this request. A successful response will include an X-IBM-Session-Ref response header that can be added as a request header to subsequent requests to specify affinity to the TSO address space holding this ENQ.
  - property: X-IBM-Session-Ref
    label: X-IBM-Session-Ref
    type: entry
    in: header
    refiner: remove_blank_header
    documentation: This header is optional; include it with the value returned from a previous X-IBM-Session-Ref response header to indicate that your request should be executed in the TSO address space that was previously reserved with a X-IBM-Obtain-ENQ request header. This address space will not be used for other requests and if not used at least once every 10 minutes it will be terminated. The X-IBM-Obtain-ENQ and X-IBM-Session-Ref headers are mutually exclusive.
  - property: X-IBM-Release-ENQ
    label: X-IBM-Release-ENQ
    type: entry
    in: header
    refiner: remove_blank_header
    documentation: This header is optional; it may be specified with a value "true" to request that the ENQ held by the associated TSO address space be released. This header must be specified along with a valid X-IBM-Session-Ref header.
