stepName: data set - write data to a zos data set or member
description: You can use this operation to write data to an existing sequential data set, or a member of a partitioned data set (PDS or PDSE). To write to an uncataloged data set, include a volume serial on the request.
endpoint: '/restfiles/ds/#{dataset-name}'
method: PUT
hasConfig: true
attachCredentials: true
basicAuth: true
resultProperty:
  show: true
  format:
    - json
    - propertySheet
  default: /myJob/createDataset
parameters:
  - property: dataset-name
    type: entry
    label: Data set name
    documentation: The name of a z/OS data set that you are going to create.
    required: 1
  - property: volser
    type: entry
    label: Volser
    documentation: A parameter that identifies the volume serials to be searched for data sets with names that match the specified dslevel parameter.
    required: 0
  - property: member-name
    type: entry
    label: Member name
    documentation: Identifies the name of the PDS or PDSE member to which to write. Include this parameter for a PDS or PDSE member write request.
    required: 0
  - property: Content-Type
    in: header
    type: entry
    label: Content Type
    refiner: remove_blank_header
    documentation: The data is interpreted according to the content-type as one of binary, text, record or 'diff -e' format according a combination of the "Content-Type" and the value of the X-IBM-Data-Type custom header, if present.
    required: 0
  - property: X-IBM-Data-Type
    label: X-IBM-Data-Type
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: text
        value: text
      - name: binary
        value: binary
      - name: record
        value: record
    documentation: When set to 'text' and "Content-Type" is "application/x-ibm-diff-e", the input consists of commands in the same format as produced by the z/OS UNIX 'diff -e' command. These commands are used to add, replace and delete lines in the target data set.
  - property: X-IBM-Migrated-Recall
    label: X-IBM-Migrated-Recall
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: wait
        value: wait
      - name: nowait
        value: nowait
      - name: record
        value: nowait
    documentation: This header is optional; use it to specify how a migrated data set is handled. By default, a migrated data set is recalled synchronously.
  - property: X-IBM-Obtain-ENQ
    label: X-IBM-Obtain-ENQ
    type: select
    in: header
    value: __IS__NOT__SET__
    refiner: convert_not_set
    option:
      - name: not set
        value: __IS__NOT__SET__
      - name: EXCL
        value: EXCL
      - name: SHRW
        value: SHRW        
    documentation: This header is optional; set it to one of the following values to request that a system ENQ be obtained and held after the completion of this request. If not specified, then no ENQs will be held after the completion of this request. A successful response will include an X-IBM-Session-Ref response header that can be added as a request header to subsequent requests to specify affinity to the TSO address space holding this ENQ.
  - property: X-IBM-Session-Ref
    label: X-IBM-Session-Ref
    type: entry
    in: header
    refiner: remove_blank_header
    documentation: This header is optional; include it with the value returned from a previous X-IBM-Session-Ref response header to indicate that your request should be executed in the TSO address space that was previously reserved with a X-IBM-Obtain-ENQ request header. This address space will not be used for other requests and if not used at least once every 10 minutes it will be terminated. The X-IBM-Obtain-ENQ and X-IBM-Session-Ref headers are mutually exclusive.
  - property: X-IBM-Release-ENQ
    label: X-IBM-Release-ENQ
    type: entry
    in: header
    refiner: remove_blank_header
    documentation: This header is optional; it may be specified with a value "true" to request that the ENQ held by the associated TSO address space be released. This header must be specified along with a valid X-IBM-Session-Ref header.
  - property: stored-data
    label: Data
    type: textarea
    in: body
    documentation: The data to write to dataset.

